### ISSUE TITLE
Akun Github AGB'24-Senin

### ISSUE THREAD

**Issue by sainsdataikopin** [sevinurafni/ST1101_2C1#1]

**Comment by sainsdataikopin** [comment]
Nama Lengkap - NRP - akun github

**Comment by pashawahyuwijaya** [comment]
Pasha Wahyu Wijaya 2C1240060 https://github.com/pashawahyuwijaya

**Comment by rezaramadan29** [comment]
REZA PUTRA RAMADAN SIMARMATA - 2C1240067-https://github.com/rezaramadan29

**Comment by IrfanPratamaUlayo** [comment]
Irfan Pratama Ulayo - 2C1240062 - https://github.com/IrfanPratamaUlayo

**Comment by SaniaNurunnisaHaq** [comment]
Sania Nurunnisa Haq - 2C1240058
https://github.com/SaniaNurunnisaHaq

**Comment by Rahelsiagian21** [comment]
Rahel Manda Sari Br. Siagian - 2C1240063
https://github.com/Rahelsiagian21

**Comment by Arzelianeha** [comment]
Arzelia Neha 2C1240047  https://github.com/Arzelianeha

**Comment by naylacahyaputri** [comment]
Nayla cahya putri 2C1240068 https://github.com/naylacahyaputri

**Comment by raihanahana07** [comment]
Raihana Rahmadani -2C1240061
https://github.com/raihanahana07

**Comment by fxxdaisy** [comment]
Firda gustia - 2C1240066
https://github.com/fxxdaisy

**Comment by zaki-rmd** [comment]
Zaki Ramadan-2C1240059- https://github.com/zaki-rmd

**Comment by Helgaltrin** [comment]
Helgaltrin Melani Apaseray_2C1240064_https://github.com/Helgaltrin

**Comment by rahmadriski** [comment]
Rahmad riski_2C1240054_https://github.com/rahmadriski

**Comment by Mnurfhadlaazhar** [comment]
mnurfhadlaazhar - 2c1240065 - https://github.com/Mnurfhadlaazhar

**Comment by nikitasinaga** [comment]
Nikita Rachelena Sinaga_2C1240056_https://github.com/nikitasinaga

**Comment by wahyuwaryani** [comment]
Wahyu Waryani 2C1240053 https://github.com/wahyuwaryani

**Comment by Sawaludinn** [comment]
sawaludin 2C1240055 ttps://github.com/Sawaludinn
