### ISSUE TITLE
Akun Github AGB'24-Selasa

### ISSUE THREAD

**Issue by sainsdataikopin** [sevinurafni/ST1101_2C1#3]
Nama - NRP - Nama akun github

**Comment by panpanii** [comment]
Nurafisah Pani _ 2C1240049 - https://github.com/panpanii

**Comment by noviadwiputri21** [comment]
Novia Dwi Putri - 2C1240042 - https://github.com/noviadwiputri21

**Comment by intanprtwi** [comment]
Intan Pratiwi - 2C1240007 - https://github.com/intanprtwi

**Comment by maulanaYanto** [comment]
Maulana Apri Yanto - 2C1240037 - https://github.com/maulanaYanto

**Comment by muhammadbachtiarrifai** [comment]
Muhammad Bachtiar Rifa'i - 2C1240048https://github.com/muhammadbachtiarrifai

**Comment by muhammadfitrialananda** [comment]
Muhammad Fitrial Ananda - 2C1240046 - https://github.com/muhammadfitrialananda

**Comment by zikriramadhan1** [comment]
Zikri Ramadhan - 2C1240040 - https://github.com/zikriramadhan1

**Comment by MYSTH253** [comment]
Tian Hadi Bahtiar - 2C1240039 - https://github.com/MYSTH253

**Comment by Sitimunirotuss** [comment]
Siti Munirotus Sholihah-2C1240043-https://github.com/Sitimunirotuss

**Comment by githubSELIA** [comment]
selia - 2C1240041 - https://github.com/githubSELIA

**Comment by MUNIR691** [comment]
M.Misbahul Munir - 2C1240050 - https://github.com/MUNIR691

**Comment by UlvaInayatulIftakhiyah** [comment]
Ulva Inayatul Iftakhiyah - 2C1240044 - https://github.com/UlvaInayatulIftakhiyah

**Comment by Chintyasiantury** [comment]
Sintia Sianturi 2C1240052 https://github.com/Chintyasiantury

**Comment by Arzelianeha** [comment]
Arzelia Neha 2C1240047 https://github.com/Arzelianeha

**Comment by MisbahulMunir01** [comment]
Muhammad Misbahul Munir
https://github.com/MisbahulMunir01/M.Misbahul-Munir

**Comment by AbymasBehhGaulMenn** [comment]
Muhammad Abi Masykur_2C1240045 
https://github.com/AbymasBehhGaulMenn
