### ISSUE TITLE
Quiz - Senin

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/ST1101_2C1#36]
Format file: NRP_Q1.pdf
Waktu pengerjaan: 100 menit
Closed Book

[Quiz AGB - Senin.pdf](https://github.com/user-attachments/files/17612059/Quiz.AGB.-.Senin.pdf)

**Comment by zaki-rmd** [comment]
NAMA : ZAKI RAMADAN
NRP     : 2C1240059
FILE     :  [ZAKI RAMADAN_2C1240059_Q1.pdf](https://github.com/user-attachments/files/17612977/ZAKI.RAMADAN_2C1240059_Q1.pdf)

**Comment by zaki-rmd** [comment]
nama : zaki ramadan
nrp    : 2C1240059
file    : [zaki ramadan_2c1240059_Q1.pdf](https://github.com/user-attachments/files/17613055/zaki.ramadan_2c1240059_Q1.pdf)

**Comment by SaniaNurunnisaHaq** [comment]
nama : Sania Nurunnisa Haq
NRP : 2C1240058
[sania nurunnisa haq_quiz 1.pdf](https://github.com/user-attachments/files/17613057/sania.nurunnisa.haq_quiz.1.pdf)

**Comment by nizarramadhani** [comment]
Nama : Nizar Ramadhani
Nrp : 2C1240057
[2C1240057_Q1 (Nizar Ramadhani).pdf](https://github.com/user-attachments/files/17613058/2C1240057_Q1.Nizar.Ramadhani.pdf)

**Comment by wahyuwaryani** [comment]
[Wahyu Waryani_2C1240053.pdf](https://github.com/user-attachments/files/17613061/Wahyu.Waryani_2C1240053.pdf)
Nama : Wahyu Waryani
NRP : 2C1240053

**Comment by Rahelsiagian21** [comment]
Nama: Rahel
NRP : 2C1240063
[Rahel Manda Sari Br,. Siagian_2c1240063_Q1.pdf](https://github.com/user-attachments/files/17613062/Rahel.Manda.Sari.Br.Siagian_2c1240063_Q1.pdf)

**Comment by naylacahyaputri** [comment]
[Nayla Cahya Putri_2C1240068.pdf](https://github.com/user-attachments/files/17613070/Nayla.Cahya.Putri_2C1240068.pdf)
Nama: Nayla Cahya Putri
NRP: 2C1240068

**Comment by Mnurfhadlaazhar** [comment]
[Nama_muhammad nur fhadla azhar_2C1240065.pdf](https://github.com/user-attachments/files/17613072/Nama_muhammad.nur.fhadla.azhar_2C1240065.pdf)

NAMA:MUHAMMAD NUR FHADLA AZHAR
NRP:2C1240065

**Comment by Helgaltrin** [comment]
Nama : Helgaltrin Melani
NRP : 2C1240064
[HELGALTRIN-2C1240064.xlsx](https://github.com/user-attachments/files/17613077/HELGALTRIN-2C1240064.xlsx)

**Comment by pashawahyuwijaya** [comment]
[QUIZ_PASHA WAHYU WIJAYA_2C1240060.pdf](https://github.com/user-attachments/files/17613099/QUIZ_PASHA.WAHYU.WIJAYA_2C1240060.pdf)

NAMA: PASHA WAHYU WIJAYA
NRP: 2C1240060

**Comment by raihanahana07** [comment]
Nama : Raihana Rahmadani
NRP: 2C1240061
[Raihana Rahmadani_2C1240061.pdf](https://github.com/user-attachments/files/17613103/Raihana.Rahmadani_2C1240061.pdf)

**Comment by Sawaludinn** [comment]
[2C1240055_SAWALUDIN_Q1.docx](https://github.com/user-attachments/files/17613105/2C1240055_SAWALUDIN_Q1.docx)
NAMA : SAWALUDIN
NRP    :2C1240055

**Comment by Helgaltrin** [comment]
NAMA : HELGALTRIN MELANI APASERAY
NRP : 2C1240064
[Helgaltrin Melani Apaseray_2C1240064.pdf](https://github.com/user-attachments/files/17613111/Helgaltrin.Melani.Apaseray_2C1240064.pdf)

**Comment by fxxdaisy** [comment]
Nama: Firda Gustia
NRP: 2C1240066
[FIRDAGUSTIA_2C1240066_Q1.xlsx.pdf](https://github.com/user-attachments/files/17613131/FIRDAGUSTIA_2C1240066_Q1.xlsx.pdf)

**Comment by nikitasinaga** [comment]
[NIKITA RACHELENA SINAGA 2C1240056.pdf](https://github.com/user-attachments/files/17613140/NIKITA.RACHELENA.SINAGA.2C1240056.pdf)
NIKITA RACHELENA SINAGA 2C1240056

**Comment by IrfanPratamaUlayo** [comment]
[QUIZ_Irfan Pratama Ulayo_2C1240062.pdf](https://github.com/user-attachments/files/17613147/QUIZ_Irfan.Pratama.Ulayo_2C1240062.pdf)

NAMA : IRFAN PRATAMA ULAYO
NRP : 2C1240062

**Comment by rahmadriski** [comment]
[Rahmad riski_2C1240054_Quis.pdf](https://github.com/user-attachments/files/17613151/Rahmad.riski_2C1240054_Quis.pdf)

NAMA: Rahmad Riski
NRP : 2C1240054

**Comment by wahyuwaryani** [comment]
[Wahyu Waryani_2C1240053.pdf](https://github.com/user-attachments/files/17613158/Wahyu.Waryani_2C1240053.pdf)
Nama : Wahyu Waryani
NRP : 2C1240053
