### ISSUE TITLE
Quiz - Rabu

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/ST1101_2C1#38]
Format file: NRP_Q1.pdf
Waktu pengerjaan: 100 menit
Closed Book

[Quiz AGB - Rabu.pdf](https://github.com/user-attachments/files/17639532/Quiz.AGB.-.Rabu.pdf)

**Comment by azzurasagala** [comment]
NAMA: AZZURA KARTIKA PUTRI SAGALA
NRP; 2C1240035
[AZZURA KARTIKA PUTRI SAGLA_2C1240034_QUIZ1.docx](https://github.com/user-attachments/files/17644655/AZZURA.KARTIKA.PUTRI.SAGLA_2C1240034_QUIZ1.docx)

**Comment by Rayyinahafsah** [comment]
NAMA : RAYYINA HAFSAH NOOR PUTRIYA
NRP : 2C1240035
[Rayyina Hafsah Noor Putriya_2C1240035_QUIZ1.docx](https://github.com/user-attachments/files/17644669/Rayyina.Hafsah.Noor.Putriya_2C1240035_QUIZ1.docx)

**Comment by ekatrantika** [comment]
NAMA : EKA TRANTIKA SARI 
NRP : 2C1240038 
[1.ekatrantikasari_2C1240038_QUIZ1.pdf](https://github.com/user-attachments/files/17644763/1.ekatrantikasari_2C1240038_QUIZ1.pdf)

**Comment by Alieframdhan** [comment]
NAMA ; alief ramdhan ferdiansyah
NRP : 2c1240072
[alief raamdhan_2C1240072_quiz1.docx](https://github.com/user-attachments/files/17644813/alief.raamdhan_2C1240072_quiz1.docx)
[alieframdhan_2C1240072.xlsx](https://github.com/user-attachments/files/17644816/alieframdhan_2C1240072.xlsx)

**Comment by ricardoyustisio** [comment]
Nama : Ricardo Yustisio 
Nrp     : 2C1240036 
[Ricardo Yustisio - 2C1240036 - quiz 1.docx](https://github.com/user-attachments/files/17644910/Ricardo.Yustisio.-.2C1240036.-.quiz.1.docx)
[ricardo quiz 1.xlsx](https://github.com/user-attachments/files/17644923/ricardo.quiz.1.xlsx)

**Comment by UlvaInayatulIftakhiyah** [comment]
[NandaAzmiNurfadhilah_2C1240070_QUIZ1.docx](https://github.com/user-attachments/files/17644945/NandaAzmiNurfadhilah_2C1240070_QUIZ1.docx)

**Comment by ketrinsimanjuntak09** [comment]
NAMA : ketrin enjelina simanjuntak
NRP : 2C1240071
[ketrin_2C1240071_Quis1.docx](https://github.com/user-attachments/files/17644964/ketrin_2C1240071_Quis1.docx)

**Comment by NandaAzmiNurfadhilah** [comment]
[NandaAzmiNurfadhilah_2C1240070_QUIZ1.docx](https://github.com/user-attachments/files/17644965/NandaAzmiNurfadhilah_2C1240070_QUIZ1.docx)

**Comment by NandaAzmiNurfadhilah** [comment]
Nama : Nanda Azmi Nurfadhilah 
NRP : 2C1240070
[NandaAzmiNurfadhilah_2C1240070_QUIZ1.docx](https://github.com/user-attachments/files/17644972/NandaAzmiNurfadhilah_2C1240070_QUIZ1.docx)
