### ISSUE TITLE
Quiz - Kamis

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/ST1101_2C1#39]
Format file: NRP_Q2.pdf
Waktu pengerjaan: 100 menit
Closed Book

[Quiz AGB - Kamis.pdf](https://github.com/user-attachments/files/17653725/Quiz.AGB.-.Kamis.pdf)

**Comment by ramapirdaus** [comment]
[quizz 1 rama pirdaus-2C1240001 2.docx](https://github.com/user-attachments/files/17654936/quizz.1.rama.pirdaus-2C1240001.2.docx)
rama pirdaus
2c1240001

**Comment by KRISBIANTO** [comment]
KRISBIANTO
2C1240015
[
[KRISBIANTO_2C1240015_QUIZ1.pdf](https://github.com/user-attachments/files/17654940/KRISBIANTO_2C1240015_QUIZ1.pdf)
](url)

**Comment by NandaAzmiNurfadhilah** [comment]
Nama : Daniel siagian
NRP : 2C1240011
[Danielsiagian_2C124001_qius 1.pdf](https://github.com/user-attachments/files/17654952/Danielsiagian_2C124001_qius.1.pdf)

**Comment by KRISBIANTO** [comment]
KRISBIANTO
2C1240015
[KRISBIANTO_2C1240015_QUIZ1.pdf](https://github.com/user-attachments/files/17654953/KRISBIANTO_2C1240015_QUIZ1.pdf)

**Comment by nubiaadrisoeripto** [comment]
Nubia Adri Soeripto
2C1240003
[Uploading Nubia Adri Soeripto_2C1240003_Quiz1.pdf…]()

**Comment by adamsalgazali** [comment]
Adams Algazali
2C1240017
[Uploading Adams Algazali_2C1240017_Quiz1.pdf…]()

**Comment by danielsiagian12** [comment]
Nama : Daniel siagian
NRP : 2C1240011
[Uploading Danielsiagian_2C124001_qius 1.pdf…]()

**Comment by mutiianyayu** [comment]
NYIAYU MUTIA RAMADHANI
2C1240012
[NYIAYUMUTIARAMADHANI-2C12400112-QUISAGORITMA.pdf](https://github.com/user-attachments/files/17654976/NYIAYUMUTIARAMADHANI-2C12400112-QUISAGORITMA.pdf)

**Comment by danielsiagian12** [comment]
Nama : Daniel siagian
NRP : 2C1240011
[Danielsiagian_2C124001_qius 1.pdf](https://github.com/user-attachments/files/17654992/Danielsiagian_2C124001_qius.1.pdf)

**Comment by GloriaLarasati1311** [comment]
Gloria Larasati
2C1240014
[Quiz Algoritma_Gloria Larasati.pdf](https://github.com/user-attachments/files/17654991/Quiz.Algoritma_Gloria.Larasati.pdf)

**Comment by ikhsanrphimat2299** [comment]
Nama : Ikhsan Rohimat
NRP : 2C1240002 
[Ikhsan Rohimat_2C1240002_Quiz1.pdf](https://github.com/user-attachments/files/17654997/Ikhsan.Rohimat_2C1240002_Quiz1.pdf)

**Comment by nubiaadrisoeripto** [comment]
Nubia Adri Soeripto
2C1240003
[Nubia Adri Soeripto_2C1240003_Quiz1.pdf](https://github.com/user-attachments/files/17654998/Nubia.Adri.Soeripto_2C1240003_Quiz1.pdf)

**Comment by manuelnababan99** [comment]
Manuel nababan
2C1240005
[MANUEL Y T N_2C1240005_QUIZ1.pdf](https://github.com/user-attachments/files/17655000/MANUEL.Y.T.N_2C1240005_QUIZ1.pdf)

**Comment by FalisaAdi** [comment]
Nama: Falisa Adi
NRP:2C1240016
[Falisa adi.pdf](https://github.com/user-attachments/files/17655007/Falisa.adi.pdf)

**Comment by JeniArianti2001** [comment]
JENI ARIANTI
2C1240010
[JENI ARIANTI- 2C1240010 QUIZ1.pdf](https://github.com/user-attachments/files/17655017/JENI.ARIANTI-.2C1240010.QUIZ1.pdf)

**Comment by monicts123** [comment]
Nama : Monica Three Selvia
NRP : 2C1240013
[MONICA THREE SELVIA_2C1240013_QUIZ1.pdf](https://github.com/user-attachments/files/17655026/MONICA.THREE.SELVIA_2C1240013_QUIZ1.pdf)

**Comment by deniikopin123** [comment]
Nama: Deni Dangiang Bagja
NRP: 2C1240008
[Nama Deni Dangiang Bagja NRP 2C1240008.pdf](https://github.com/user-attachments/files/17655036/Nama.Deni.Dangiang.Bagja.NRP.2C1240008.pdf)

**Comment by jiasumimasen** [comment]
nama : zya naswa nur azmi 
NRP : 2C1240006
[zya naswa_2C1240006_QUIZ.pdf](https://github.com/user-attachments/files/17655043/zya.naswa_2C1240006_QUIZ.pdf)

**Comment by AgniaMiftah5** [comment]
Nama : Agnia Miftah M
NRP : 2C1240009
[AgniaMiftah_2C1240009.pdf](https://github.com/user-attachments/files/17655052/AgniaMiftah_2C1240009.pdf)
